// Wraps the OpenNext-generated worker to also export our own Durable
// Object (PLAN.md §15 / Phase 12) — `.open-next/worker.js` is regenerated
// on every build and has no way to know about app-level bindings, so this
// file (pointed at by `main` in wrangler.jsonc / wrangler.dev.jsonc) is
// the one that doesn't get overwritten.
// See https://opennext.js.org/cloudflare/howtos/custom-worker.
//
// It also handles ALL of the live-bids traffic directly, ahead of Next:
//
//  - `/api/live-bids/ws` — a Next Route Handler can't return the 101
//    upgrade (OpenNext bridges API routes through a Node-ServerResponse
//    shim that rejects any status outside 200-599), so this has always
//    been here.
//  - `/api/live-bids/state` and `/api/officer/live-bids/{push,heartbeat,
//    clear}` moved here 2026-08-30. They call the LiveAuctionSession
//    Durable Object, and doing that *from Next server code* is a double
//    hop under OpenNext local dev — workerd → the Node loopback that runs
//    Next → back to workerd for the DO RPC — which can't sustain the
//    parser app's poll loop and takes `wrangler dev` down with it (see
//    CLAUDE.md "Hard-won gotchas"). Handled here, the DO RPC never leaves
//    workerd. Also one less hop in production. Auth is the same — the
//    officer x-api-key check and the session+membership check — just
//    invoked with `env` directly instead of via getCloudflareContext().
//
// The finalize path (`POST /api/officer/bids`) still calls the DO's
// /clear from its Next route: that's one call per round, not a loop, so it
// doesn't have the sustained-load problem.

import { and, desc, eq, sql } from "drizzle-orm";
import { drizzle } from "drizzle-orm/d1";

import { createAuth } from "./src/auth";
import * as schema from "./src/db";
import { bids as bidsTable, characters, lootEvents, users } from "./src/db";
import { verifyOfficerApiKey } from "./src/lib/api-key-auth";
import { fetchIsMemberAllowed } from "./src/lib/discord-verify";
import { getStandings, rebuildAllStandings } from "./src/lib/epgp/standings";
import { markRequest, perfEnabled, setPerfEnabled } from "./src/lib/perf";
import { reconcileMainPointers } from "./src/lib/players";

// @ts-ignore — .open-next/worker.js is generated by `opennextjs-cloudflare
// build` and won't exist until then; @ts-ignore (not @ts-expect-error)
// because that also makes it harmless once the file does exist locally.
import { default as handler } from "./.open-next/worker.js";

function cfOf(request: Request) {
  return (request as unknown as { cf?: Record<string, unknown> }).cf;
}

async function handleLiveBidsWebSocket(request: Request, env: CloudflareEnv): Promise<Response> {
  if (request.headers.get("Upgrade") !== "websocket") {
    return new Response("Expected a WebSocket upgrade", { status: 426 });
  }

  const auth = createAuth(env, cfOf(request));
  const session = await auth.api.getSession({ headers: request.headers });
  if (!session) {
    return Response.json({ error: "Not signed in." }, { status: 401 });
  }

  const db = drizzle(env.DATABASE, { schema });
  if (!(await fetchIsMemberAllowed(db, session.user.id))) {
    return Response.json({ error: "Access denied." }, { status: 403 });
  }

  // Pass the resolved user id to the DO so it can filter this viewer's
  // dismissed rounds out of every frame on this socket (LT-32). The second
  // arg copies method + the Upgrade headers; the URL comes from the first.
  const stub = liveAuctionStub(env);
  const doUrl = `https://live-auction-session/ws?userId=${encodeURIComponent(session.user.id)}`;
  return stub.fetch(new Request(doUrl, request));
}

// GET /api/live-bids/state — every member (same bar as the WS view).
async function handleLiveBidsState(request: Request, env: CloudflareEnv): Promise<Response> {
  const auth = createAuth(env, cfOf(request));
  const session = await auth.api.getSession({ headers: request.headers });
  if (!session) return Response.json({ error: "Not signed in." }, { status: 401 });

  const db = drizzle(env.DATABASE, { schema });
  if (!(await fetchIsMemberAllowed(db, session.user.id))) {
    return Response.json({ error: "Not allowed." }, { status: 403 });
  }

  // ?userId= so the DO's snapshot already has this viewer's dismissed
  // rounds (LT-32) filtered out — same view the WS frames give them.
  const doUrl = `https://live-auction-session/state?userId=${encodeURIComponent(session.user.id)}`;
  const resp = await liveAuctionStub(env).fetch(doUrl);
  if (!resp.ok) return Response.json({ error: "Live session unavailable." }, { status: 502 });
  return new Response(await resp.text(), { headers: { "Content-Type": "application/json" } });
}

// POST /api/live-bids/dismiss — every member (same bar as /state). LT-32:
// this is the member-facing "Dismiss" on a resolved card, and it's now a
// PER-ACCOUNT dismiss — the DO records it against this viewer's user id
// (persisted, survives their refresh and a DO eviction) and keeps showing
// the round to everyone else. It clears itself when the round leaves the
// board (12h auto-sweep, a re-drop of the same item, or an officer /clear).
// The old localStorage-only client hack is gone. Forwarding without a
// `userId` still triggers the DO's legacy global force-clear, but nothing
// does that now.
async function handleLiveBidsDismiss(request: Request, env: CloudflareEnv): Promise<Response> {
  const auth = createAuth(env, cfOf(request));
  const session = await auth.api.getSession({ headers: request.headers });
  if (!session) return Response.json({ error: "Not signed in." }, { status: 401 });

  const db = drizzle(env.DATABASE, { schema });
  if (!(await fetchIsMemberAllowed(db, session.user.id))) {
    return Response.json({ error: "Not allowed." }, { status: 403 });
  }

  let itemName: unknown;
  let all: unknown;
  try {
    ({ itemName, all } = (await request.json()) as { itemName?: unknown; all?: unknown });
  } catch {
    return Response.json({ error: "Invalid JSON body." }, { status: 400 });
  }
  // `all: true` — the board's "Clear all" (2026-09-10): dismiss every
  // resolved card for this viewer in one call.
  if (all === true) return forwardToDO(env, "dismiss", { all: true, userId: session.user.id });
  if (typeof itemName !== "string" || !itemName.trim()) {
    return Response.json({ error: "`itemName` is required." }, { status: 400 });
  }
  return forwardToDO(env, "dismiss", { itemName: itemName.trim(), userId: session.user.id });
}

// POST /api/officer/live-bids/{push,heartbeat,clear,resolve} — officer x-api-key.
async function handleOfficerLiveBids(request: Request, env: CloudflareEnv, action: string): Promise<Response> {
  const auth = await verifyOfficerApiKey(request, env, cfOf(request));
  if ("error" in auth) return Response.json({ error: auth.error }, { status: auth.status });

  const db = drizzle(env.DATABASE, { schema });
  const officerName = await resolveCollectedByName(db, auth.userId);

  let body: Record<string, unknown> = {};
  try {
    body = (await request.json()) as Record<string, unknown>;
  } catch {
    if (action === "push" || action === "resolve") return Response.json({ error: "Invalid JSON body." }, { status: 400 });
    // heartbeat/clear tolerate an empty body
  }

  if (action === "push") {
    if (typeof body.itemName !== "string" || !body.itemName.trim()) {
      return Response.json({ error: "`itemName` is required." }, { status: 400 });
    }

    // Snapshot push (parser >= v0.1.13): the officer's whole current bid
    // list for this item, every tick — see the DO's /push handler for why.
    // Priority for every name is resolved in ONE roster query (COLLATE
    // NOCASE, matching the characters unique index) + the cached standings.
    if (Array.isArray(body.bids)) {
      const raw = body.bids as unknown[];
      const tells: { characterName: string; tier: string; occurredAt: string }[] = [];
      for (const r of raw.slice(0, 200)) {
        if (!r || typeof r !== "object") continue;
        const b = r as { characterName?: unknown; tier?: unknown; occurredAt?: unknown };
        if (typeof b.characterName !== "string" || !b.characterName.trim()) continue;
        if (typeof b.tier !== "string" || typeof b.occurredAt !== "string") continue;
        if (Number.isNaN(new Date(b.occurredAt).getTime())) continue;
        tells.push({ characterName: b.characterName.trim(), tier: b.tier.trim(), occurredAt: b.occurredAt });
      }
      const priorityByName = new Map<string, number | null>();
      const names = [...new Set(tells.map((t) => t.characterName))];
      if (names.length > 0) {
        const [chars, totals] = await Promise.all([
          db
            .select({ name: characters.name, playerId: characters.playerId })
            .from(characters)
            .where(sql`${characters.name} COLLATE NOCASE IN (${sql.join(names.map((n) => sql`${n}`), sql`, `)})`),
          getStandings(db),
        ]);
        for (const c of chars) {
          priorityByName.set(c.name.toLowerCase(), c.playerId != null ? (totals.get(c.playerId)?.priorityRating ?? null) : null);
        }
      }
      return forwardToDO(env, "push", {
        itemName: (body.itemName as string).trim(),
        bids: tells.map((t) => ({ ...t, priorityRating: priorityByName.get(t.characterName.toLowerCase()) ?? null })),
        officerId: auth.userId,
        officerName: collectedByFromBody(body, officerName),
      });
    }

    for (const f of ["characterName", "tier"] as const) {
      if (typeof body[f] !== "string" || !(body[f] as string).trim()) {
        return Response.json({ error: `\`${f}\` is required.` }, { status: 400 });
      }
    }
    if (typeof body.occurredAt !== "string" || Number.isNaN(new Date(body.occurredAt).getTime())) {
      return Response.json({ error: "`occurredAt` must be a valid date." }, { status: 400 });
    }

    // Best-effort priority — an unmatched name still gets pushed live with
    // priorityRating null rather than dropped (same as the officer's own
    // review table handling a "no match").
    const characterName = (body.characterName as string).trim();
    const [character] = await db.select({ playerId: characters.playerId }).from(characters).where(eq(characters.name, characterName));
    let priorityRating: number | null = null;
    if (character?.playerId != null) {
      const totals = await getStandings(db);
      priorityRating = totals.get(character.playerId)?.priorityRating ?? null;
    }

    return forwardToDO(env, "push", {
      itemName: (body.itemName as string).trim(),
      characterName,
      tier: (body.tier as string).trim(),
      occurredAt: body.occurredAt,
      priorityRating,
      officerId: auth.userId,
      officerName: collectedByFromBody(body, officerName),
    });
  }

  if (action === "resolve") {
    if (typeof body.itemName !== "string" || !body.itemName.trim()) {
      return Response.json({ error: "`itemName` is required." }, { status: 400 });
    }
    // The parser sends the full final bid list (`bids`, every entry flagged
    // isWinner or not) as of 2026-09-01 so the resolved card keeps showing
    // every bidder + priority, not just the winner. Older clients send only
    // `winners` — still supported.
    const rawBids = Array.isArray(body.bids) ? body.bids : [];
    const rawWinners = Array.isArray(body.winners) ? body.winners : [];

    // Prefer the Priority Rating snapshotted at bid time. POST
    // /api/officer/bids runs immediately before this and writes
    // bids.priority_snapshot for every bidder *before* the winner's GP
    // charge lands. If we recomputed PR here from live standings instead,
    // the winner would show post-charge (lower) while the losers stay
    // pre-charge — making the winner look like they had the worst
    // priority on the resolved card. Read the snapshot back, keyed by
    // character name, and only fall back to a live lookup for a name that
    // has no bid row (e.g. an unmatched bid).
    const snapshotByName = new Map<string, number>();
    try {
      const itemLower = body.itemName.trim().toLowerCase();
      const [latestEvent] = await db
        .select({ id: lootEvents.id })
        .from(lootEvents)
        .where(sql`lower(${lootEvents.itemName}) = ${itemLower}`)
        .orderBy(desc(lootEvents.id))
        .limit(1);
      if (latestEvent) {
        const snapRows = await db
          .select({ name: characters.name, snap: bidsTable.prioritySnapshot })
          .from(bidsTable)
          .innerJoin(characters, eq(characters.id, bidsTable.characterId))
          .where(eq(bidsTable.lootEventId, latestEvent.id));
        for (const r of snapRows) if (typeof r.snap === "number") snapshotByName.set(r.name.toLowerCase(), r.snap);
      }
    } catch {
      // best-effort — fall back to the live lookup below
    }

    // Live standings, only fetched if some name has no snapshot to use.
    let totals: Awaited<ReturnType<typeof getStandings>> | null = null;
    const priorityCache = new Map<string, number | null>();
    async function priorityFor(name: string): Promise<number | null> {
      const snap = snapshotByName.get(name.toLowerCase());
      if (snap !== undefined) return snap;
      const cached = priorityCache.get(name.toLowerCase());
      if (cached !== undefined) return cached;
      let priorityRating: number | null = null;
      if (!totals && (rawBids.length || rawWinners.length)) totals = await getStandings(db);
      const [character] = await db.select({ playerId: characters.playerId }).from(characters).where(eq(characters.name, name));
      if (character?.playerId != null && totals) priorityRating = totals.get(character.playerId)?.priorityRating ?? null;
      priorityCache.set(name.toLowerCase(), priorityRating);
      return priorityRating;
    }

    // One row per character, same as the live "collecting" card and the
    // parser's own ResolveLatestPerCharacter: a winner row always wins the
    // slot, otherwise the later entry does (the parser sends them in
    // occurredAt order). Keeps a "changed my mind" / superseded bid from
    // showing as a second row on the resolved card.
    const byName = new Map<string, { characterName: string; tier: string; isWinner: boolean; occurredAt: string | undefined }>();
    for (const b of rawBids) {
      if (!b || typeof b !== "object") continue;
      const cb = b as { characterName?: unknown; tier?: unknown; isWinner?: unknown; occurredAt?: unknown };
      if (typeof cb.characterName !== "string" || typeof cb.tier !== "string") continue;
      const name = cb.characterName.trim();
      const isWinner = cb.isWinner === true;
      const prev = byName.get(name.toLowerCase());
      if (prev && prev.isWinner && !isWinner) continue;
      byName.set(name.toLowerCase(), {
        characterName: name,
        tier: cb.tier.trim(),
        isWinner,
        occurredAt: typeof cb.occurredAt === "string" ? cb.occurredAt : undefined,
      });
    }

    const bids = [];
    const winnersFromBids = [];
    for (const row of byName.values()) {
      const priorityRating = await priorityFor(row.characterName);
      bids.push({ characterName: row.characterName, tier: row.tier, priorityRating, occurredAt: row.occurredAt });
      if (row.isWinner) winnersFromBids.push({ characterName: row.characterName, tier: row.tier, priorityRating });
    }

    // Winners: derived from the bid list's isWinner flags when present,
    // otherwise the legacy explicit `winners` array.
    let winners = winnersFromBids;
    if (winners.length === 0 && rawWinners.length) {
      for (const w of rawWinners) {
        if (!w || typeof w !== "object") continue;
        const cw = w as { characterName?: unknown; tier?: unknown };
        if (typeof cw.characterName !== "string" || typeof cw.tier !== "string") continue;
        const name = cw.characterName.trim();
        winners.push({ characterName: name, tier: cw.tier.trim(), priorityRating: await priorityFor(name) });
      }
    }

    // POST /api/officer/bids ran just before this and charged the winner's
    // GP + refreshed standings, so getStandings() here is current. Every
    // OTHER still-collecting round on the board is showing pre-charge
    // priority for anyone that charge moved — hand the DO a fresh
    // name→priority map so it can re-price those rounds and an officer
    // picking a winner elsewhere doesn't do it off a stale number (which is
    // how one character could sweep several items before EPGP caught up).
    let repriceAll: Record<string, number> | undefined;
    try {
      const s = await getStandings(db);
      const chars = await db.select({ name: characters.name, playerId: characters.playerId }).from(characters);
      const m: Record<string, number> = {};
      for (const c of chars) {
        if (c.playerId == null) continue;
        const pr = s.get(c.playerId)?.priorityRating;
        if (typeof pr === "number") m[c.name.toLowerCase()] = pr;
      }
      repriceAll = m;
    } catch {
      // best-effort — the resolve still goes through without the reprice
    }

    return forwardToDO(env, "resolve", {
      itemName: body.itemName.trim(),
      winners,
      bids,
      repriceAll,
      officerId: auth.userId,
      officerName: collectedByFromBody(body, officerName),
    });
  }

  if (action === "heartbeat") {
    return forwardToDO(env, "heartbeat", {
      itemName: typeof body.itemName === "string" ? body.itemName : undefined,
      officerId: auth.userId,
      officerName,
    });
  }

  // clear — officerId scopes a bare (no itemName) clear to just this
  // officer's rounds, so one officer quitting their app can't wipe every
  // other officer's live round off the board.
  return forwardToDO(env, "clear", {
    itemName: typeof body.itemName === "string" ? body.itemName : undefined,
    officerId: auth.userId,
  });
}

async function forwardToDO(env: CloudflareEnv, path: string, payload: unknown): Promise<Response> {
  try {
    const resp = await liveAuctionStub(env).fetch(`https://live-auction-session/${path}`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload),
    });
    if (!resp.ok) return Response.json({ error: "Live session rejected the request." }, { status: 502 });
  } catch {
    return Response.json({ error: "Live session unavailable." }, { status: 502 });
  }
  return Response.json({ ok: true }, { status: 200 });
}

function liveAuctionStub(env: CloudflareEnv) {
  return env.LIVE_AUCTION_SESSION.get(env.LIVE_AUCTION_SESSION.idFromName("global"));
}

// The guild's live domain. seekersofsouls.com (apex) is canonical; every
// other hostname that routes to this Worker in production — www, plus the
// old placeholder seekers.fetchinglogic.com host, kept alive only as a
// redirecting backup — 301/308s here so there's exactly one origin the app,
// its cookies, and the Discord OAuth callback ever run on. Anything not in
// this set (the canonical host itself, *.workers.dev preview builds,
// localhost dev) passes straight through.
const SLOW_REQUEST_MS = 5000;
const REQUEST_DEADLINE_MS = 25_000;

function hangResponse(): Response {
  const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="refresh" content="3"><title>Seekers of Souls</title></head><body style="margin:0;min-height:100vh;display:flex;align-items:center;justify-content:center;background:#0a0a0a;color:#e5e5e5;font-family:ui-sans-serif,system-ui,sans-serif"><div style="max-width:420px;padding:2rem;text-align:center"><h1 style="font-size:1.25rem;font-weight:700">The site took too long to respond</h1><p style="margin-top:.75rem;color:#a3a3a3;font-size:.9rem">Retrying automatically in a few seconds. If this keeps happening, let a leader know.</p><p style="margin-top:1.5rem"><a href="javascript:location.reload()" style="border-radius:9999px;background:#10b981;color:#000;padding:.5rem 1.25rem;font-weight:600;text-decoration:none">Reload now</a></p></div></body></html>`;
  return new Response(html, {
    status: 503,
    headers: { "content-type": "text/html; charset=utf-8", "cache-control": "private, no-cache, no-store, max-age=0, must-revalidate", "retry-after": "3" },
  });
}

const CANONICAL_HOST = "seekersofsouls.com";
const REDIRECT_HOSTS = new Set(["www.seekersofsouls.com", "seekers.fetchinglogic.com", "www.fetchinglogic.com"]);

function canonicalRedirect(request: Request, url: URL): Response | null {
  if (!REDIRECT_HOSTS.has(url.hostname)) return null;
  const target = new URL(url.toString());
  target.hostname = CANONICAL_HOST;
  target.protocol = "https:";
  target.port = "";
  // 308 for non-idempotent methods so a POST (a login submit, an officer
  // API call from a not-yet-updated parser) keeps its method, body, and
  // headers across the hop instead of being downgraded to GET.
  const status = request.method === "GET" || request.method === "HEAD" ? 301 : 308;
  return new Response(null, { status, headers: { Location: target.toString() } });
}

// The "collected by" label on a live-bids card (post-live-test-1 LT-07).
// Prefer the officer's own main character name over their Discord username
// — members recognise "collected by Sandrian", not a Discord handle. The
// parser also sends the exact character whose log it parsed
// (`capturedByCharacter`); when present that wins, since an officer may be
// running an alt. Falls back to the username, then a generic label.
// NOTE (2026-09-10): the "short private browser cache" that used to sit
// here (Cache-Control: private, max-age=15, stale-while-revalidate=60 on
// /roster, /dashboard, /epgp/ledger, ...) is GONE, deliberately. A Next
// client-side navigation is an RSC fetch, and when (app)/layout.tsx throws
// redirect("/login") during one of those the response is HTTP **200** with
// the redirect inside the flight payload — so a single transient "no
// session" (a cold-isolate blip, or one genuine lapse) got "go to /login"
// cached in the viewer's browser for that page for up to 75s. They'd log
// back in, click the same page, replay the cached redirect, and land on
// /login again — the "it keeps logging me out" loop, visible in the
// sessions table as logins seconds apart. Verified live with
// `curl -H 'RSC: 1' /roster` → 200 + that cache header. Speed comes from
// the server-side fixes (batched writes, standings cache), not from
// caching auth-gated responses in the browser.

async function resolveCollectedByName(db: ReturnType<typeof drizzle>, userId: string): Promise<string> {
  const [main] = await db
    .select({ name: characters.name })
    .from(characters)
    .where(and(eq(characters.ownerId, userId), eq(characters.charType, "main")))
    .limit(1);
  if (main?.name?.trim()) return main.name.trim();
  const [row] = await db.select({ username: users.username }).from(users).where(eq(users.id, userId));
  return row?.username?.trim() || "An officer";
}

function collectedByFromBody(body: Record<string, unknown>, fallback: string): string {
  const c = body.capturedByCharacter;
  return typeof c === "string" && c.trim() ? c.trim() : fallback;
}

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);

    // Phase 4 perf spike (LT-26): PERF_DEBUG=1 turns on [perf] timing logs
    // across getSession / the layout gate / getStandings. One boolean flip
    // per isolate; a no-op otherwise.
    setPerfEnabled((env as { PERF_DEBUG?: string }).PERF_DEBUG === "1");
    markRequest(url.pathname);

    const redirect = canonicalRedirect(request, url);
    if (redirect) return redirect;

    if (url.pathname === "/api/live-bids/ws") return handleLiveBidsWebSocket(request, env);
    if (url.pathname === "/api/live-bids/state" && request.method === "GET") return handleLiveBidsState(request, env);
    if (url.pathname === "/api/live-bids/dismiss" && request.method === "POST") return handleLiveBidsDismiss(request, env);

    const officer = url.pathname.match(/^\/api\/officer\/live-bids\/(push|heartbeat|clear|resolve)$/);
    if (officer && request.method === "POST") return handleOfficerLiveBids(request, env, officer[1]);

    // Always-on slow-request log (2026-09-10): a leader reported the site
    // "freezing" for 60s+ on a page load. Analytics can't tell a hung page
    // render from a long-lived WebSocket, so any non-WS request over
    // SLOW_REQUEST_MS is logged with its path, status and whether the
    // request carried a session cookie — visible in `wrangler tail` and the
    // dashboard's Workers Logs without flipping PERF_DEBUG.
    const t0 = Date.now();
    let status = 0;
    // Request deadline (2026-09-11). Workers Logs showed page renders and
    // officer API reads from three different members' networks held open
    // for 40s to 100 minutes and then "canceled" — a member whose
    // navigation fetch never returns sees a frozen tab, and Next's router
    // has no timeout of its own. There are no Suspense/loading boundaries
    // in this app, so handler.fetch doesn't resolve until the whole render
    // has, which makes a deadline on it meaningful. GET/HEAD only: a
    // timed-out write must not be retried blindly. The 503 is HTML for
    // both document and RSC requests — Next's router hard-navigates on a
    // non-RSC response, so a stuck client-side navigation becomes a fresh
    // full page load; a document request gets the same page, which
    // reloads itself. The [hang] stage/D1 lines logged in the meantime say
    // where it was stuck.
    const deadlineMs = request.method === "GET" || request.method === "HEAD" ? REQUEST_DEADLINE_MS : 0;
    let deadlineTimer: ReturnType<typeof setTimeout> | undefined;
    const deadline = deadlineMs
      ? new Promise<Response>((resolve) => {
          deadlineTimer = setTimeout(() => {
            const rsc = request.headers.has("RSC") ? " rsc" : "";
            console.warn(`[hang] ${request.method} ${url.pathname} no response after ${deadlineMs}ms; returning 503${rsc}`);
            resolve(hangResponse());
          }, deadlineMs);
        })
      : null;
    try {
      const resp = deadline ? await Promise.race([handler.fetch(request, env, ctx), deadline]) : await handler.fetch(request, env, ctx);
      status = resp.status;
      return resp;
    } catch (e) {
      status = -1;
      throw e;
    } finally {
      if (deadlineTimer) clearTimeout(deadlineTimer);
      const ms = Date.now() - t0;
      if (perfEnabled()) console.log(`[perf] request ${request.method} ${url.pathname} ${ms}ms`);
      if (ms >= SLOW_REQUEST_MS) {
        const hasCookie = (request.headers.get("cookie") ?? "").includes("better-auth.session");
        const rsc = request.headers.has("RSC") ? " rsc" : "";
        console.warn(`[slow] ${request.method} ${url.pathname} ${ms}ms status=${status} session=${hasCookie ? "yes" : "no"}${rsc}`);
      }
    }
  },

  // Two crons (wrangler.jsonc `triggers.crons`), dispatched on event.cron.
  async scheduled(event, env, ctx) {
    // "*/2 * * * *" — keep-warm ping (LT-26/LT-27; 2 min since 2026-09-10).
    // Warm the D1 binding on THIS isolate, then self-fetch the health route
    // and an app page so a render-path isolate stays hot too. Best-effort;
    // a failure just means the next real request pays a cold start.
    if (event.cron === "*/2 * * * *") {
      const warm = (async () => {
        try {
          await drizzle(env.DATABASE, { schema }).run(sql`SELECT 1`);
          // Two self-fetches: the API path, and a real app page. Next loads
          // each route's module chunk lazily, so a warm /api/health alone
          // still left the first /roster click paying that route's own
          // module evaluation + the layout/auth chain. /roster without a
          // cookie is a cheap 307 (getSession → null → redirect) that
          // evaluates exactly those modules. "manual" redirect so the
          // fetch doesn't follow it into /login.
          const [h, p] = await Promise.all([
            fetch("https://seekersofsouls.com/api/health", { headers: { "x-warm": "cron" } }),
            fetch("https://seekersofsouls.com/roster", { headers: { "x-warm": "cron" }, redirect: "manual" }),
          ]);
          console.log(`[cron] warm ping health=${h.status} page=${p.status}`);
        } catch (e) {
          console.log(`[cron] warm ping failed: ${e}`);
        }
      })();
      ctx.waitUntil(warm);
      return;
    }

    // "17 9 * * *" — nightly safety-net rebuild. refreshStandings already
    // runs on every write, so this only catches a missed hook or the
    // per-cycle-rollover shift under decay_model=legacy — and, via
    // rebuildAllStandings, re-derives characters.last_activity_at too.
    const db = drizzle(env.DATABASE, { schema });
    const { players } = await rebuildAllStandings(db);
    console.log(`[cron] rebuilt standings + last_activity for ${players} players`);

    // Prune expired session rows. better-auth's session.create.after hook
    // mints a fresh `sessions` row on every login and nothing ever deletes
    // them, so the table grows one row per login forever (84 rows / 11
    // users as of 2026-09-09, ~half already expired). Nothing reads an
    // expired row — better-auth filters on expires_at itself — this just
    // keeps the table from accreting dead rows indefinitely. Best-effort:
    // a failure here must not fail the standings rebuild above.
    try {
      const res = await db.run(
        sql`DELETE FROM sessions WHERE expires_at < strftime('%s','now')`,
      );
      console.log(`[cron] pruned ${res.meta.changes ?? 0} expired session rows`);
    } catch (e) {
      console.log(`[cron] session prune failed (non-fatal): ${e}`);
    }

    // Re-derive characters.char_type/main_character_id from
    // players.main_character_id (see reconcileMainPointers). Anything other
    // than zeros here means some write path let the two drift again — worth
    // a look at who edited what that day.
    try {
      const r = await reconcileMainPointers(db);
      console.log(`[cron] main-pointer reconcile: alts=${r.altsRetyped} mains=${r.mainsRetyped} pointers=${r.pointersSet}`);
    } catch (e) {
      console.log(`[cron] main-pointer reconcile failed (non-fatal): ${e}`);
    }
  },
} satisfies ExportedHandler<CloudflareEnv>;

export { LiveAuctionSession } from "./src/durable-objects/live-auction-session";
