// Wraps the OpenNext-generated worker to also export our own Durable
// Object (PLAN.md §15 / Phase 12) — `.open-next/worker.js` is regenerated
// on every build and has no way to know about app-level bindings, so this
// file (pointed at by `main` in wrangler.jsonc / wrangler.dev.jsonc) is
// the one that doesn't get overwritten.
// See https://opennext.js.org/cloudflare/howtos/custom-worker.
//
// It also handles ALL of the live-bids traffic directly, ahead of Next:
//
//  - `/api/live-bids/ws` — a Next Route Handler can't return the 101
//    upgrade (OpenNext bridges API routes through a Node-ServerResponse
//    shim that rejects any status outside 200-599), so this has always
//    been here.
//  - `/api/live-bids/state` and `/api/officer/live-bids/{push,heartbeat,
//    clear}` moved here 2026-08-30. They call the LiveAuctionSession
//    Durable Object, and doing that *from Next server code* is a double
//    hop under OpenNext local dev — workerd → the Node loopback that runs
//    Next → back to workerd for the DO RPC — which can't sustain the
//    parser app's poll loop and takes `wrangler dev` down with it (see
//    CLAUDE.md "Hard-won gotchas"). Handled here, the DO RPC never leaves
//    workerd. Also one less hop in production. Auth is the same — the
//    officer x-api-key check and the session+membership check — just
//    invoked with `env` directly instead of via getCloudflareContext().
//
// The finalize path (`POST /api/officer/bids`) still calls the DO's
// /clear from its Next route: that's one call per round, not a loop, so it
// doesn't have the sustained-load problem.

import { desc, eq, sql } from "drizzle-orm";
import { drizzle } from "drizzle-orm/d1";

import { createAuth } from "./src/auth";
import * as schema from "./src/db";
import { bids as bidsTable, characters, lootEvents, users } from "./src/db";
import { verifyOfficerApiKey } from "./src/lib/api-key-auth";
import { fetchIsMemberAllowed } from "./src/lib/discord-verify";
import { getStandings, rebuildAllStandings } from "./src/lib/epgp/standings";

// @ts-ignore — .open-next/worker.js is generated by `opennextjs-cloudflare
// build` and won't exist until then; @ts-ignore (not @ts-expect-error)
// because that also makes it harmless once the file does exist locally.
import { default as handler } from "./.open-next/worker.js";

function cfOf(request: Request) {
  return (request as unknown as { cf?: Record<string, unknown> }).cf;
}

async function handleLiveBidsWebSocket(request: Request, env: CloudflareEnv): Promise<Response> {
  if (request.headers.get("Upgrade") !== "websocket") {
    return new Response("Expected a WebSocket upgrade", { status: 426 });
  }

  const auth = createAuth(env, cfOf(request));
  const session = await auth.api.getSession({ headers: request.headers });
  if (!session) {
    return Response.json({ error: "Not signed in." }, { status: 401 });
  }

  const db = drizzle(env.DATABASE, { schema });
  if (!(await fetchIsMemberAllowed(db, session.user.id))) {
    return Response.json({ error: "Access denied." }, { status: 403 });
  }

  const stub = liveAuctionStub(env);
  return stub.fetch(new Request("https://live-auction-session/ws", request));
}

// GET /api/live-bids/state — every member (same bar as the WS view).
async function handleLiveBidsState(request: Request, env: CloudflareEnv): Promise<Response> {
  const auth = createAuth(env, cfOf(request));
  const session = await auth.api.getSession({ headers: request.headers });
  if (!session) return Response.json({ error: "Not signed in." }, { status: 401 });

  const db = drizzle(env.DATABASE, { schema });
  if (!(await fetchIsMemberAllowed(db, session.user.id))) {
    return Response.json({ error: "Not allowed." }, { status: 403 });
  }

  const resp = await liveAuctionStub(env).fetch("https://live-auction-session/state");
  if (!resp.ok) return Response.json({ error: "Live session unavailable." }, { status: 502 });
  return new Response(await resp.text(), { headers: { "Content-Type": "application/json" } });
}

// POST /api/live-bids/dismiss — every member (same bar as /state). Removes
// a resolved round from the shared board for EVERY viewer, not just the
// caller — that's exactly the "one person closes it, it's gone for
// everyone" behavior the leader flagged (2026-09-05). The member-facing
// Dismiss button (LiveBidsView.tsx) no longer calls this — it hides a
// resolved card locally (localStorage), per-viewer, and never touches the
// server. This endpoint is kept as a manual, shared "force clear" escape
// hatch (e.g. an officer clearing a stuck card for everyone via a direct
// call) — nothing in the UI wires it up as of this comment.
async function handleLiveBidsDismiss(request: Request, env: CloudflareEnv): Promise<Response> {
  const auth = createAuth(env, cfOf(request));
  const session = await auth.api.getSession({ headers: request.headers });
  if (!session) return Response.json({ error: "Not signed in." }, { status: 401 });

  const db = drizzle(env.DATABASE, { schema });
  if (!(await fetchIsMemberAllowed(db, session.user.id))) {
    return Response.json({ error: "Not allowed." }, { status: 403 });
  }

  let itemName: unknown;
  try {
    ({ itemName } = (await request.json()) as { itemName?: unknown });
  } catch {
    return Response.json({ error: "Invalid JSON body." }, { status: 400 });
  }
  if (typeof itemName !== "string" || !itemName.trim()) {
    return Response.json({ error: "`itemName` is required." }, { status: 400 });
  }
  return forwardToDO(env, "dismiss", { itemName: itemName.trim() });
}

// POST /api/officer/live-bids/{push,heartbeat,clear,resolve} — officer x-api-key.
async function handleOfficerLiveBids(request: Request, env: CloudflareEnv, action: string): Promise<Response> {
  const auth = await verifyOfficerApiKey(request, env, cfOf(request));
  if ("error" in auth) return Response.json({ error: auth.error }, { status: auth.status });

  const db = drizzle(env.DATABASE, { schema });
  const officerName = await resolveOfficerName(db, auth.userId);

  let body: Record<string, unknown> = {};
  try {
    body = (await request.json()) as Record<string, unknown>;
  } catch {
    if (action === "push" || action === "resolve") return Response.json({ error: "Invalid JSON body." }, { status: 400 });
    // heartbeat/clear tolerate an empty body
  }

  if (action === "push") {
    for (const f of ["itemName", "characterName", "tier"] as const) {
      if (typeof body[f] !== "string" || !(body[f] as string).trim()) {
        return Response.json({ error: `\`${f}\` is required.` }, { status: 400 });
      }
    }
    if (typeof body.occurredAt !== "string" || Number.isNaN(new Date(body.occurredAt).getTime())) {
      return Response.json({ error: "`occurredAt` must be a valid date." }, { status: 400 });
    }

    // Best-effort priority — an unmatched name still gets pushed live with
    // priorityRating null rather than dropped (same as the officer's own
    // review table handling a "no match").
    const characterName = (body.characterName as string).trim();
    const [character] = await db.select({ playerId: characters.playerId }).from(characters).where(eq(characters.name, characterName));
    let priorityRating: number | null = null;
    if (character?.playerId != null) {
      const totals = await getStandings(db);
      priorityRating = totals.get(character.playerId)?.priorityRating ?? null;
    }

    return forwardToDO(env, "push", {
      itemName: (body.itemName as string).trim(),
      characterName,
      tier: (body.tier as string).trim(),
      occurredAt: body.occurredAt,
      priorityRating,
      officerId: auth.userId,
      officerName,
    });
  }

  if (action === "resolve") {
    if (typeof body.itemName !== "string" || !body.itemName.trim()) {
      return Response.json({ error: "`itemName` is required." }, { status: 400 });
    }
    // The parser sends the full final bid list (`bids`, every entry flagged
    // isWinner or not) as of 2026-09-01 so the resolved card keeps showing
    // every bidder + priority, not just the winner. Older clients send only
    // `winners` — still supported.
    const rawBids = Array.isArray(body.bids) ? body.bids : [];
    const rawWinners = Array.isArray(body.winners) ? body.winners : [];

    // Prefer the Priority Rating snapshotted at bid time. POST
    // /api/officer/bids runs immediately before this and writes
    // bids.priority_snapshot for every bidder *before* the winner's GP
    // charge lands. If we recomputed PR here from live standings instead,
    // the winner would show post-charge (lower) while the losers stay
    // pre-charge — making the winner look like they had the worst
    // priority on the resolved card. Read the snapshot back, keyed by
    // character name, and only fall back to a live lookup for a name that
    // has no bid row (e.g. an unmatched bid).
    const snapshotByName = new Map<string, number>();
    try {
      const itemLower = body.itemName.trim().toLowerCase();
      const [latestEvent] = await db
        .select({ id: lootEvents.id })
        .from(lootEvents)
        .where(sql`lower(${lootEvents.itemName}) = ${itemLower}`)
        .orderBy(desc(lootEvents.id))
        .limit(1);
      if (latestEvent) {
        const snapRows = await db
          .select({ name: characters.name, snap: bidsTable.prioritySnapshot })
          .from(bidsTable)
          .innerJoin(characters, eq(characters.id, bidsTable.characterId))
          .where(eq(bidsTable.lootEventId, latestEvent.id));
        for (const r of snapRows) if (typeof r.snap === "number") snapshotByName.set(r.name.toLowerCase(), r.snap);
      }
    } catch {
      // best-effort — fall back to the live lookup below
    }

    // Live standings, only fetched if some name has no snapshot to use.
    let totals: Awaited<ReturnType<typeof getStandings>> | null = null;
    const priorityCache = new Map<string, number | null>();
    async function priorityFor(name: string): Promise<number | null> {
      const snap = snapshotByName.get(name.toLowerCase());
      if (snap !== undefined) return snap;
      const cached = priorityCache.get(name.toLowerCase());
      if (cached !== undefined) return cached;
      let priorityRating: number | null = null;
      if (!totals && (rawBids.length || rawWinners.length)) totals = await getStandings(db);
      const [character] = await db.select({ playerId: characters.playerId }).from(characters).where(eq(characters.name, name));
      if (character?.playerId != null && totals) priorityRating = totals.get(character.playerId)?.priorityRating ?? null;
      priorityCache.set(name.toLowerCase(), priorityRating);
      return priorityRating;
    }

    // One row per character, same as the live "collecting" card and the
    // parser's own ResolveLatestPerCharacter: a winner row always wins the
    // slot, otherwise the later entry does (the parser sends them in
    // occurredAt order). Keeps a "changed my mind" / superseded bid from
    // showing as a second row on the resolved card.
    const byName = new Map<string, { characterName: string; tier: string; isWinner: boolean; occurredAt: string | undefined }>();
    for (const b of rawBids) {
      if (!b || typeof b !== "object") continue;
      const cb = b as { characterName?: unknown; tier?: unknown; isWinner?: unknown; occurredAt?: unknown };
      if (typeof cb.characterName !== "string" || typeof cb.tier !== "string") continue;
      const name = cb.characterName.trim();
      const isWinner = cb.isWinner === true;
      const prev = byName.get(name.toLowerCase());
      if (prev && prev.isWinner && !isWinner) continue;
      byName.set(name.toLowerCase(), {
        characterName: name,
        tier: cb.tier.trim(),
        isWinner,
        occurredAt: typeof cb.occurredAt === "string" ? cb.occurredAt : undefined,
      });
    }

    const bids = [];
    const winnersFromBids = [];
    for (const row of byName.values()) {
      const priorityRating = await priorityFor(row.characterName);
      bids.push({ characterName: row.characterName, tier: row.tier, priorityRating, occurredAt: row.occurredAt });
      if (row.isWinner) winnersFromBids.push({ characterName: row.characterName, tier: row.tier, priorityRating });
    }

    // Winners: derived from the bid list's isWinner flags when present,
    // otherwise the legacy explicit `winners` array.
    let winners = winnersFromBids;
    if (winners.length === 0 && rawWinners.length) {
      for (const w of rawWinners) {
        if (!w || typeof w !== "object") continue;
        const cw = w as { characterName?: unknown; tier?: unknown };
        if (typeof cw.characterName !== "string" || typeof cw.tier !== "string") continue;
        const name = cw.characterName.trim();
        winners.push({ characterName: name, tier: cw.tier.trim(), priorityRating: await priorityFor(name) });
      }
    }

    return forwardToDO(env, "resolve", {
      itemName: body.itemName.trim(),
      winners,
      bids,
      officerId: auth.userId,
      officerName,
    });
  }

  if (action === "heartbeat") {
    return forwardToDO(env, "heartbeat", {
      itemName: typeof body.itemName === "string" ? body.itemName : undefined,
      officerId: auth.userId,
      officerName,
    });
  }

  // clear
  return forwardToDO(env, "clear", {
    itemName: typeof body.itemName === "string" ? body.itemName : undefined,
  });
}

async function forwardToDO(env: CloudflareEnv, path: string, payload: unknown): Promise<Response> {
  try {
    const resp = await liveAuctionStub(env).fetch(`https://live-auction-session/${path}`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload),
    });
    if (!resp.ok) return Response.json({ error: "Live session rejected the request." }, { status: 502 });
  } catch {
    return Response.json({ error: "Live session unavailable." }, { status: 502 });
  }
  return Response.json({ ok: true }, { status: 200 });
}

function liveAuctionStub(env: CloudflareEnv) {
  return env.LIVE_AUCTION_SESSION.get(env.LIVE_AUCTION_SESSION.idFromName("global"));
}

// The guild's live domain. seekersofsouls.com (apex) is canonical; every
// other hostname that routes to this Worker in production — www, plus the
// old placeholder seekers.fetchinglogic.com host, kept alive only as a
// redirecting backup — 301/308s here so there's exactly one origin the app,
// its cookies, and the Discord OAuth callback ever run on. Anything not in
// this set (the canonical host itself, *.workers.dev preview builds,
// localhost dev) passes straight through.
const CANONICAL_HOST = "seekersofsouls.com";
const REDIRECT_HOSTS = new Set(["www.seekersofsouls.com", "seekers.fetchinglogic.com", "www.fetchinglogic.com"]);

function canonicalRedirect(request: Request, url: URL): Response | null {
  if (!REDIRECT_HOSTS.has(url.hostname)) return null;
  const target = new URL(url.toString());
  target.hostname = CANONICAL_HOST;
  target.protocol = "https:";
  target.port = "";
  // 308 for non-idempotent methods so a POST (a login submit, an officer
  // API call from a not-yet-updated parser) keeps its method, body, and
  // headers across the hop instead of being downgraded to GET.
  const status = request.method === "GET" || request.method === "HEAD" ? 301 : 308;
  return new Response(null, { status, headers: { Location: target.toString() } });
}

async function resolveOfficerName(db: ReturnType<typeof drizzle>, userId: string): Promise<string> {
  const [row] = await db.select({ username: users.username }).from(users).where(eq(users.id, userId));
  return row?.username?.trim() || "An officer";
}

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);

    const redirect = canonicalRedirect(request, url);
    if (redirect) return redirect;

    if (url.pathname === "/api/live-bids/ws") return handleLiveBidsWebSocket(request, env);
    if (url.pathname === "/api/live-bids/state" && request.method === "GET") return handleLiveBidsState(request, env);
    if (url.pathname === "/api/live-bids/dismiss" && request.method === "POST") return handleLiveBidsDismiss(request, env);

    const officer = url.pathname.match(/^\/api\/officer\/live-bids\/(push|heartbeat|clear|resolve)$/);
    if (officer && request.method === "POST") return handleOfficerLiveBids(request, env, officer[1]);

    return handler.fetch(request, env, ctx);
  },

  // Nightly safety-net rebuild (cron in wrangler.jsonc). refreshStandings
  // already runs on every write, so this only catches a missed hook or the
  // per-cycle-rollover shift under decay_model=legacy — and, via
  // rebuildAllStandings, re-derives characters.last_activity_at too.
  async scheduled(_event, env) {
    const db = drizzle(env.DATABASE, { schema });
    const { players } = await rebuildAllStandings(db);
    console.log(`[cron] rebuilt standings + last_activity for ${players} players`);
  },
} satisfies ExportedHandler<CloudflareEnv>;

export { LiveAuctionSession } from "./src/durable-objects/live-auction-session";
