// Wraps the OpenNext-generated worker to also export our own Durable
// Object (PLAN.md §15 / Phase 12) — `.open-next/worker.js` is regenerated
// on every build and has no way to know about app-level bindings, so this
// file (pointed at by `main` in wrangler.jsonc / wrangler.dev.jsonc) is
// the one that doesn't get overwritten.
// See https://opennext.js.org/cloudflare/howtos/custom-worker.
//
// Also handles the live-bids WebSocket upgrade directly, ahead of Next —
// confirmed locally that a Next.js Route Handler can't do this itself:
// OpenNext bridges API routes through a Node-`http.ServerResponse`-style
// shim (for Node-API compatibility) that rejects any status outside
// 200-599, so the 101 Switching Protocols response a WebSocket upgrade
// needs never reaches the real Workers runtime — it 500s before that. This
// intercepts the one route that needs a raw Response before Next's router
// (and that shim) ever sees it; every other route still goes through Next
// exactly as before, including POST /api/officer/live-bids/push, which is
// a normal JSON response and has no such problem.

import { drizzle } from "drizzle-orm/d1";

import { createAuth } from "./src/auth";
import { fetchIsMemberAllowed } from "./src/lib/discord-verify";

// @ts-ignore — .open-next/worker.js is generated by `opennextjs-cloudflare
// build` and won't exist until then; @ts-ignore (not @ts-expect-error)
// because that also makes it harmless once the file does exist locally.
import { default as handler } from "./.open-next/worker.js";

async function handleLiveBidsWebSocket(request: Request, env: CloudflareEnv): Promise<Response> {
  if (request.headers.get("Upgrade") !== "websocket") {
    return new Response("Expected a WebSocket upgrade", { status: 426 });
  }

  const auth = createAuth(env, (request as unknown as { cf?: Record<string, unknown> }).cf);
  const session = await auth.api.getSession({ headers: request.headers });
  if (!session) {
    return Response.json({ error: "Not signed in." }, { status: 401 });
  }

  const db = drizzle(env.DATABASE);
  if (!(await fetchIsMemberAllowed(db, session.user.id))) {
    return Response.json({ error: "Access denied." }, { status: 403 });
  }

  const id = env.LIVE_AUCTION_SESSION.idFromName("global");
  const stub = env.LIVE_AUCTION_SESSION.get(id);
  // `new Request(url, request)` swaps in the DO-internal path the DO's
  // fetch() routes on while keeping the original request's headers
  // (Upgrade/Connection/Sec-WebSocket-*) that make this an actual upgrade.
  return stub.fetch(new Request("https://live-auction-session/ws", request));
}

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    if (url.pathname === "/api/live-bids/ws") {
      return handleLiveBidsWebSocket(request, env);
    }
    return handler.fetch(request, env, ctx);
  },
} satisfies ExportedHandler<CloudflareEnv>;

export { LiveAuctionSession } from "./src/durable-objects/live-auction-session";
